[package]
name = "password_manager_backend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17"
serde = "1.0"
serde_derive = "1.0"
hex = "0.4"
ic-cdk-macros = "0.17.1"
